addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.4.3")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.3.4")
addSbtPlugin("com.github.sbt"  % "sbt-release"  % "1.0.15")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype" % "3.9.7")
addSbtPlugin("com.github.sbt"       % "sbt-pgp"      % "2.1.2")
