addSbtPlugin("pl.project13.scala"  % "sbt-jmh"        % "0.4.7")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("com.github.sbt"      % "sbt-ci-release" % "1.5.12")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"    % "0.10.0")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"       % "2.6.0")
addSbtPlugin("com.timushev.sbt"    % "sbt-updates"    % "0.6.4")
