addSbtPlugin("pl.project13.scala"  % "sbt-jmh"        % "0.4.3")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("com.github.sbt"      % "sbt-release"    % "1.1.0")
addSbtPlugin("com.github.sbt"      % "sbt-ci-release" % "1.5.10")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"    % "0.10.0")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"       % "2.3.6")
